### ISSUE TITLE
Can't reach Node.js application

### ISSUE THREAD

**Issue by vasisiop** [Zzocker/book-Sharing-fabric#2]
I am testing this example on ubuntu 16.04. Everything works fine but when i execute  "nodemon ./testapi/api.js" command i cannot access node app. On the browser i receive this message "Cannot GET /"

**Comment by Zzocker** [comment]
I'm unable to understand the error which your facing , can you send more details ( like sc of error or logs ) to my personal mail at pkspritam10@gmail.com

Peace
